### ISSUE TITLE
Material theme for kendo-jquery and mvc

### ISSUE THREAD

**Issue by mgmiles** [telerik/kendo-theme-material#20]
Is there a roadmap for the availability of the material theme including ripple and floating label support for the Kendo UI jquery and MVC products?

**Comment by joneff** [comment]
The material theme is currently in development and that's why it's not included in the distributions of kendo-jquery and the MVC / Core counterparts.

As soon as it's in a completed state it will be made available.

As far as floating labels and ripples are concerned, things are a bit more complicated -- while the styles for both micro components will be present, we'll  need to add the additional interaction logic in kendo-jquery.

@bergenhem and @eeasss do we have a tentative ETA on the material theme?

**Comment by bergenhem** [comment]
The current plan is to have the Material theme ready for the jQuery, MVC, and .NET Core flavors by R2 of 2018. This will be a part of our Sass-based themes that are available for the current Kendo UI offerings (jQuery, MVC, Core, Angular, React, and Vue).
